TOPICS_LIST = [
    ("Variable declaration and initialization", "Python"),
    ("Variable declaration and initialization", "Java"),
    ("Variable declaration and initialization", "C++"),
    ("Variable declaration and initialization", "Kotlin"),
    ("Data types (int, float, string, boolean)", "Python"),
    ("Data types (int, float, String, boolean)", "Java"),
    ("Data types (int, float, string, bool)", "C++"),
    ("Data types (Int, Float, String, Boolean)", "Kotlin"),
    ("Type conversion and casting", "Python"),
    ("Type conversion and casting", "Java"),
    ("Type conversion and casting", "C++"),
    ("Type conversion and casting", "Kotlin"),
    ("Arithmetic operations", "Python"),
    ("Arithmetic operations", "Java"),
    ("Arithmetic operations", "C++"),
    ("Arithmetic operations", "Kotlin"),
    ("Comparison operators", "Python"),
    ("Comparison operators", "Java"),
    ("Comparison operators", "C++"),
    ("Comparison operators", "Kotlin"),
    ("Logical operators", "Python"),
    ("Logical operators", "Java"),
    ("Logical operators", "C++"),
    ("Logical operators", "Kotlin"),
    ("Conditional statements (if-else)", "Python"),
    ("Conditional statements (if-else)", "Java"),
    ("Conditional statements (if-else)", "C++"),
    ("Conditional statements (if-else)", "Kotlin"),
    ("Switch/case statements", "Java"),
    ("Switch/case statements", "C++"),
    ("When expression", "Kotlin"),
    ("Loops (for, while)", "Python"),
    ("Loops (for, while, do-while)", "Java"),
    ("Loops (for, while, do-while)", "C++"),
    ("Loops (for, while, do-while)", "Kotlin"),
    ("Break and continue statements", "Python"),
    ("Break and continue statements", "Java"),
    ("Break and continue statements", "C++"),
    ("Break and continue statements", "Kotlin"),
    ("Function definition and calling", "Python"),
    ("Method definition and calling", "Java"),
    ("Function definition and calling", "C++"),
    ("Function definition and calling", "Kotlin"),
    ("Function parameters and return values", "Python"),
    ("Method parameters and return values", "Java"),
    ("Function parameters and return values", "C++"),
    ("Function parameters and return values", "Kotlin"),
    ("Recursion", "Python"),
    ("Recursion", "Java"),
    ("Recursion", "C++"),
    ("Recursion", "Kotlin"),
    ("Lambda functions", "Python"),
    ("Lambda expressions", "Java"),
    ("Lambda expressions", "C++"),
    ("Lambda expressions", "Kotlin"),
    ("List manipulation", "Python"),
    ("ArrayList manipulation", "Java"),
    ("Vector manipulation", "C++"),
    ("List manipulation", "Kotlin"),
    ("List comprehensions", "Python"),
    ("Stream API", "Java"),
    ("Range-based for loops", "C++"),
    ("List comprehensions", "Kotlin"),
    ("Dictionaries", "Python"),
    ("HashMap", "Java"),
    ("std::map", "C++"),
    ("Map", "Kotlin"),
    ("Sets", "Python"),
    ("HashSet", "Java"),
    ("std::set", "C++"),
    ("Set", "Kotlin"),
    ("Tuples", "Python"),
    ("Pair and Triple", "Kotlin"),
    ("std::tuple", "C++"),
    ("String manipulation and formatting", "Python"),
    ("String manipulation and formatting", "Java"),
    ("String manipulation and formatting", "C++"),
    ("String manipulation and formatting", "Kotlin"),
    ("Regular expressions", "Python"),
    ("Regular expressions", "Java"),
    ("Regular expressions", "C++"),
    ("Regular expressions", "Kotlin"),
    ("File I/O operations", "Python"),
    ("File I/O operations", "Java"),
    ("File I/O operations", "C++"),
    ("File I/O operations", "Kotlin"),
    ("Exception handling (try-except)", "Python"),
    ("Exception handling (try-catch)", "Java"),
    ("Exception handling (try-catch)", "C++"),
    ("Exception handling (try-catch)", "Kotlin"),
    ("Custom exceptions", "Python"),
    ("Custom exceptions", "Java"),
    ("Custom exceptions", "C++"),
    ("Custom exceptions", "Kotlin"),
    ("Class definition and instantiation", "Python"),
    ("Class definition and instantiation", "Java"),
    ("Class definition and instantiation", "C++"),
    ("Class definition and instantiation", "Kotlin"),
    ("Inheritance and polymorphism", "Python"),
    ("Inheritance and polymorphism", "Java"),
    ("Inheritance and polymorphism", "C++"),
    ("Inheritance and polymorphism", "Kotlin"),
    ("Encapsulation and access modifiers", "Python"),
    ("Encapsulation and access modifiers", "Java"),
    ("Encapsulation and access modifiers", "C++"),
    ("Encapsulation and access modifiers", "Kotlin"),
    ("Abstract classes and interfaces", "Python"),
    ("Abstract classes and interfaces", "Java"),
    ("Abstract classes and pure virtual functions", "C++"),
    ("Abstract classes and interfaces", "Kotlin"),
    ("Static methods and class methods", "Python"),
    ("Static methods", "Java"),
    ("Static methods", "C++"),
    ("Companion objects", "Kotlin"),
    ("Operator overloading", "Python"),
    ("Operator overloading", "C++"),
    ("Operator overloading", "Kotlin"),
    ("Generators", "Python"),
    ("Sequence", "Kotlin"),
    ("Coroutines", "Kotlin"),
    ("Decorators", "Python"),
    ("Annotations", "Java"),
    ("Attributes", "C++"),
    ("Annotations", "Kotlin")
]